//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ficha5_HolidayWebService.HolidayService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.sapo.pt/Metadata/Holiday", ConfigurationName="HolidayService.HolidaySoap")]
    public interface HolidaySoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/Metadata/Holiday/GetAllHolidays", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ficha5_HolidayWebService.HolidayService.Holiday[] GetAllHolidays(int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/Metadata/Holiday/GetAllHolidays", ReplyAction="*")]
        System.Threading.Tasks.Task<ficha5_HolidayWebService.HolidayService.Holiday[]> GetAllHolidaysAsync(int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/Metadata/Holiday/GetCarnival", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ficha5_HolidayWebService.HolidayService.Holiday GetCarnival(int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/Metadata/Holiday/GetCarnival", ReplyAction="*")]
        System.Threading.Tasks.Task<ficha5_HolidayWebService.HolidayService.Holiday> GetCarnivalAsync(int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/Metadata/Holiday/GetCorpusChristi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ficha5_HolidayWebService.HolidayService.Holiday GetCorpusChristi(int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/Metadata/Holiday/GetCorpusChristi", ReplyAction="*")]
        System.Threading.Tasks.Task<ficha5_HolidayWebService.HolidayService.Holiday> GetCorpusChristiAsync(int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/Metadata/Holiday/GetEaster", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ficha5_HolidayWebService.HolidayService.Holiday GetEaster(int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/Metadata/Holiday/GetEaster", ReplyAction="*")]
        System.Threading.Tasks.Task<ficha5_HolidayWebService.HolidayService.Holiday> GetEasterAsync(int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/Metadata/Holiday/GetGoodFriday", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ficha5_HolidayWebService.HolidayService.Holiday GetGoodFriday(int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/Metadata/Holiday/GetGoodFriday", ReplyAction="*")]
        System.Threading.Tasks.Task<ficha5_HolidayWebService.HolidayService.Holiday> GetGoodFridayAsync(int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/Metadata/Holiday/GetHolidaysByMunicipalityId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ficha5_HolidayWebService.HolidayService.Holiday[] GetHolidaysByMunicipalityId(int year, string municipalityId, bool includeNational);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/Metadata/Holiday/GetHolidaysByMunicipalityId", ReplyAction="*")]
        System.Threading.Tasks.Task<ficha5_HolidayWebService.HolidayService.Holiday[]> GetHolidaysByMunicipalityIdAsync(int year, string municipalityId, bool includeNational);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/Metadata/Holiday/GetLocalHolidays", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ficha5_HolidayWebService.HolidayService.Holiday[] GetLocalHolidays(int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/Metadata/Holiday/GetLocalHolidays", ReplyAction="*")]
        System.Threading.Tasks.Task<ficha5_HolidayWebService.HolidayService.Holiday[]> GetLocalHolidaysAsync(int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/Metadata/Holiday/GetNationalHolidays", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ficha5_HolidayWebService.HolidayService.Holiday[] GetNationalHolidays(int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/Metadata/Holiday/GetNationalHolidays", ReplyAction="*")]
        System.Threading.Tasks.Task<ficha5_HolidayWebService.HolidayService.Holiday[]> GetNationalHolidaysAsync(int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/Metadata/Holiday/GetRegionalHolidays", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ficha5_HolidayWebService.HolidayService.Holiday[] GetRegionalHolidays(int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/Metadata/Holiday/GetRegionalHolidays", ReplyAction="*")]
        System.Threading.Tasks.Task<ficha5_HolidayWebService.HolidayService.Holiday[]> GetRegionalHolidaysAsync(int year);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sapo.pt/Metadata/Holiday")]
    public partial class Holiday : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private System.DateTime dateField;
        
        private bool dateFieldSpecified;
        
        private string descriptionField;
        
        private HolidayType typeField;
        
        private bool typeFieldSpecified;
        
        private Municipality municipalityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
                this.RaisePropertyChanged("DateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public HolidayType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
                this.RaisePropertyChanged("TypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public Municipality Municipality {
            get {
                return this.municipalityField;
            }
            set {
                this.municipalityField = value;
                this.RaisePropertyChanged("Municipality");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sapo.pt/Metadata/Holiday")]
    public enum HolidayType {
        
        /// <remarks/>
        National,
        
        /// <remarks/>
        Municipal,
        
        /// <remarks/>
        Regional,
        
        /// <remarks/>
        Religious,
        
        /// <remarks/>
        Optional,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sapo.pt/Metadata/Holiday")]
    public partial class Municipality : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HolidaySoapChannel : ficha5_HolidayWebService.HolidayService.HolidaySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HolidaySoapClient : System.ServiceModel.ClientBase<ficha5_HolidayWebService.HolidayService.HolidaySoap>, ficha5_HolidayWebService.HolidayService.HolidaySoap {
        
        public HolidaySoapClient() {
        }
        
        public HolidaySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HolidaySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HolidaySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HolidaySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ficha5_HolidayWebService.HolidayService.Holiday[] GetAllHolidays(int year) {
            return base.Channel.GetAllHolidays(year);
        }
        
        public System.Threading.Tasks.Task<ficha5_HolidayWebService.HolidayService.Holiday[]> GetAllHolidaysAsync(int year) {
            return base.Channel.GetAllHolidaysAsync(year);
        }
        
        public ficha5_HolidayWebService.HolidayService.Holiday GetCarnival(int year) {
            return base.Channel.GetCarnival(year);
        }
        
        public System.Threading.Tasks.Task<ficha5_HolidayWebService.HolidayService.Holiday> GetCarnivalAsync(int year) {
            return base.Channel.GetCarnivalAsync(year);
        }
        
        public ficha5_HolidayWebService.HolidayService.Holiday GetCorpusChristi(int year) {
            return base.Channel.GetCorpusChristi(year);
        }
        
        public System.Threading.Tasks.Task<ficha5_HolidayWebService.HolidayService.Holiday> GetCorpusChristiAsync(int year) {
            return base.Channel.GetCorpusChristiAsync(year);
        }
        
        public ficha5_HolidayWebService.HolidayService.Holiday GetEaster(int year) {
            return base.Channel.GetEaster(year);
        }
        
        public System.Threading.Tasks.Task<ficha5_HolidayWebService.HolidayService.Holiday> GetEasterAsync(int year) {
            return base.Channel.GetEasterAsync(year);
        }
        
        public ficha5_HolidayWebService.HolidayService.Holiday GetGoodFriday(int year) {
            return base.Channel.GetGoodFriday(year);
        }
        
        public System.Threading.Tasks.Task<ficha5_HolidayWebService.HolidayService.Holiday> GetGoodFridayAsync(int year) {
            return base.Channel.GetGoodFridayAsync(year);
        }
        
        public ficha5_HolidayWebService.HolidayService.Holiday[] GetHolidaysByMunicipalityId(int year, string municipalityId, bool includeNational) {
            return base.Channel.GetHolidaysByMunicipalityId(year, municipalityId, includeNational);
        }
        
        public System.Threading.Tasks.Task<ficha5_HolidayWebService.HolidayService.Holiday[]> GetHolidaysByMunicipalityIdAsync(int year, string municipalityId, bool includeNational) {
            return base.Channel.GetHolidaysByMunicipalityIdAsync(year, municipalityId, includeNational);
        }
        
        public ficha5_HolidayWebService.HolidayService.Holiday[] GetLocalHolidays(int year) {
            return base.Channel.GetLocalHolidays(year);
        }
        
        public System.Threading.Tasks.Task<ficha5_HolidayWebService.HolidayService.Holiday[]> GetLocalHolidaysAsync(int year) {
            return base.Channel.GetLocalHolidaysAsync(year);
        }
        
        public ficha5_HolidayWebService.HolidayService.Holiday[] GetNationalHolidays(int year) {
            return base.Channel.GetNationalHolidays(year);
        }
        
        public System.Threading.Tasks.Task<ficha5_HolidayWebService.HolidayService.Holiday[]> GetNationalHolidaysAsync(int year) {
            return base.Channel.GetNationalHolidaysAsync(year);
        }
        
        public ficha5_HolidayWebService.HolidayService.Holiday[] GetRegionalHolidays(int year) {
            return base.Channel.GetRegionalHolidays(year);
        }
        
        public System.Threading.Tasks.Task<ficha5_HolidayWebService.HolidayService.Holiday[]> GetRegionalHolidaysAsync(int year) {
            return base.Channel.GetRegionalHolidaysAsync(year);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.sapo.pt/Metadata/Holiday", ConfigurationName="HolidayService.HolidaySoapSecure")]
    public interface HolidaySoapSecure {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/Metadata/Holiday/GetAllHolidays", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ficha5_HolidayWebService.HolidayService.Holiday[] GetAllHolidays(int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/Metadata/Holiday/GetAllHolidays", ReplyAction="*")]
        System.Threading.Tasks.Task<ficha5_HolidayWebService.HolidayService.Holiday[]> GetAllHolidaysAsync(int year);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HolidaySoapSecureChannel : ficha5_HolidayWebService.HolidayService.HolidaySoapSecure, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HolidaySoapSecureClient : System.ServiceModel.ClientBase<ficha5_HolidayWebService.HolidayService.HolidaySoapSecure>, ficha5_HolidayWebService.HolidayService.HolidaySoapSecure {
        
        public HolidaySoapSecureClient() {
        }
        
        public HolidaySoapSecureClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HolidaySoapSecureClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HolidaySoapSecureClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HolidaySoapSecureClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ficha5_HolidayWebService.HolidayService.Holiday[] GetAllHolidays(int year) {
            return base.Channel.GetAllHolidays(year);
        }
        
        public System.Threading.Tasks.Task<ficha5_HolidayWebService.HolidayService.Holiday[]> GetAllHolidaysAsync(int year) {
            return base.Channel.GetAllHolidaysAsync(year);
        }
    }
}
