//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ficha5_ClientBookstore.BookstoreServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/ficha5_ServerBookstore")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ficha5_ClientBookstore.BookstoreServiceReference.BookCategory CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ficha5_ClientBookstore.BookstoreServiceReference.BookCategory Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((this.CategoryField.Equals(value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookCategory", Namespace="http://schemas.datacontract.org/2004/07/ficha5_ServerBookstore")]
    public enum BookCategory : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WEB = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CHILDREN = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SCIENCE = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ROMANCE = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BIOGRAPHIES = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OTHER = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookstoreServiceReference.IServiceBookstore")]
    public interface IServiceBookstore {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookstore/AddBook", ReplyAction="http://tempuri.org/IServiceBookstore/AddBookResponse")]
        void AddBook(ficha5_ClientBookstore.BookstoreServiceReference.Book newBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookstore/AddBook", ReplyAction="http://tempuri.org/IServiceBookstore/AddBookResponse")]
        System.Threading.Tasks.Task AddBookAsync(ficha5_ClientBookstore.BookstoreServiceReference.Book newBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookstore/GetBooks", ReplyAction="http://tempuri.org/IServiceBookstore/GetBooksResponse")]
        ficha5_ClientBookstore.BookstoreServiceReference.Book[] GetBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookstore/GetBooks", ReplyAction="http://tempuri.org/IServiceBookstore/GetBooksResponse")]
        System.Threading.Tasks.Task<ficha5_ClientBookstore.BookstoreServiceReference.Book[]> GetBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookstore/GetBooksByCategory", ReplyAction="http://tempuri.org/IServiceBookstore/GetBooksByCategoryResponse")]
        ficha5_ClientBookstore.BookstoreServiceReference.Book[] GetBooksByCategory(ficha5_ClientBookstore.BookstoreServiceReference.BookCategory category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookstore/GetBooksByCategory", ReplyAction="http://tempuri.org/IServiceBookstore/GetBooksByCategoryResponse")]
        System.Threading.Tasks.Task<ficha5_ClientBookstore.BookstoreServiceReference.Book[]> GetBooksByCategoryAsync(ficha5_ClientBookstore.BookstoreServiceReference.BookCategory category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookstore/GetBookByTitle", ReplyAction="http://tempuri.org/IServiceBookstore/GetBookByTitleResponse")]
        ficha5_ClientBookstore.BookstoreServiceReference.Book GetBookByTitle(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookstore/GetBookByTitle", ReplyAction="http://tempuri.org/IServiceBookstore/GetBookByTitleResponse")]
        System.Threading.Tasks.Task<ficha5_ClientBookstore.BookstoreServiceReference.Book> GetBookByTitleAsync(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookstore/GetBooksByTitle", ReplyAction="http://tempuri.org/IServiceBookstore/GetBooksByTitleResponse")]
        ficha5_ClientBookstore.BookstoreServiceReference.Book[] GetBooksByTitle(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookstore/GetBooksByTitle", ReplyAction="http://tempuri.org/IServiceBookstore/GetBooksByTitleResponse")]
        System.Threading.Tasks.Task<ficha5_ClientBookstore.BookstoreServiceReference.Book[]> GetBooksByTitleAsync(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookstore/DeleteBook", ReplyAction="http://tempuri.org/IServiceBookstore/DeleteBookResponse")]
        bool DeleteBook(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookstore/DeleteBook", ReplyAction="http://tempuri.org/IServiceBookstore/DeleteBookResponse")]
        System.Threading.Tasks.Task<bool> DeleteBookAsync(string title);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceBookstoreChannel : ficha5_ClientBookstore.BookstoreServiceReference.IServiceBookstore, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceBookstoreClient : System.ServiceModel.ClientBase<ficha5_ClientBookstore.BookstoreServiceReference.IServiceBookstore>, ficha5_ClientBookstore.BookstoreServiceReference.IServiceBookstore {
        
        public ServiceBookstoreClient() {
        }
        
        public ServiceBookstoreClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceBookstoreClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBookstoreClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBookstoreClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddBook(ficha5_ClientBookstore.BookstoreServiceReference.Book newBook) {
            base.Channel.AddBook(newBook);
        }
        
        public System.Threading.Tasks.Task AddBookAsync(ficha5_ClientBookstore.BookstoreServiceReference.Book newBook) {
            return base.Channel.AddBookAsync(newBook);
        }
        
        public ficha5_ClientBookstore.BookstoreServiceReference.Book[] GetBooks() {
            return base.Channel.GetBooks();
        }
        
        public System.Threading.Tasks.Task<ficha5_ClientBookstore.BookstoreServiceReference.Book[]> GetBooksAsync() {
            return base.Channel.GetBooksAsync();
        }
        
        public ficha5_ClientBookstore.BookstoreServiceReference.Book[] GetBooksByCategory(ficha5_ClientBookstore.BookstoreServiceReference.BookCategory category) {
            return base.Channel.GetBooksByCategory(category);
        }
        
        public System.Threading.Tasks.Task<ficha5_ClientBookstore.BookstoreServiceReference.Book[]> GetBooksByCategoryAsync(ficha5_ClientBookstore.BookstoreServiceReference.BookCategory category) {
            return base.Channel.GetBooksByCategoryAsync(category);
        }
        
        public ficha5_ClientBookstore.BookstoreServiceReference.Book GetBookByTitle(string title) {
            return base.Channel.GetBookByTitle(title);
        }
        
        public System.Threading.Tasks.Task<ficha5_ClientBookstore.BookstoreServiceReference.Book> GetBookByTitleAsync(string title) {
            return base.Channel.GetBookByTitleAsync(title);
        }
        
        public ficha5_ClientBookstore.BookstoreServiceReference.Book[] GetBooksByTitle(string title) {
            return base.Channel.GetBooksByTitle(title);
        }
        
        public System.Threading.Tasks.Task<ficha5_ClientBookstore.BookstoreServiceReference.Book[]> GetBooksByTitleAsync(string title) {
            return base.Channel.GetBooksByTitleAsync(title);
        }
        
        public bool DeleteBook(string title) {
            return base.Channel.DeleteBook(title);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteBookAsync(string title) {
            return base.Channel.DeleteBookAsync(title);
        }
    }
}
